### ISSUE TITLE
Mobile ordering

### ISSUE THREAD

**Issue by sg00dwin** [benjaminapetersen/layout.attrs#4]
How can we target specific ordering at multiple resolutions?

``` html
<div mobile="main-axis:center order:2">
```

or 

``` html
<div sm-main-axis="center" sm-order="2">
```

**Comment by benjaminapetersen** [comment]
Thinking about this in re #5 as well, so its consistent.  Some thoughts:

``` html
<div layout="row" md-layout="column" main-axis="center" sm-main-axis="end" order="2" sm-order="1"></div>
```

Curious how much more CSS this will generate.

**Comment by benjaminapetersen** [comment]
So what would probably be good here is to compile all the items that really need to be responsive.  

```
layout -> sm-layout md-layout lg-layout
main-axis -> etc
cross-axis -> etc
order -> etc
```

sufficient? bet there are a good # of use cases.
