### ISSUE TITLE
Naming of specific resolution attributes

### ISSUE THREAD

**Issue by sg00dwin** [benjaminapetersen/layout.attrs#5]
Thoughts on replacing mobile, tablet, laptop, desktop with sm, md, lg

```
[mobile="column"] becomes [sm-flex-direction="column"] ...
```

**Comment by benjaminapetersen** [comment]
Some more ideas:

``` html
<div layout="row" md-layout="column"></div>
<div row md-layout="column"></div>
<div row sm-direction="column"></div>
```

I think the first one makes the most sense, pinning `row, column` to an attribute called `layout` (Polymer used layout at one point, so this seems intuitive).  Might be a better word?

**Comment by benjaminapetersen** [comment]
Update: have more or less deprecated `layout`. Now:

``` html
<div column></div>
<div row></div>
```

Would have to resurrect to keep the above concept possible

**Comment by benjaminapetersen** [comment]
@rhamilto for ideas as well

**Comment by rhamilto** [comment]
👍 to @sg00dwin's proposal as it's the most immediate.  it ties together size and css property and i knew exactly what it meant when i read it.
