### ISSUE TITLE
Default flex value has changed - effects IE 10

### ISSUE THREAD

**Issue by sg00dwin** [benjaminapetersen/layout.attrs#6]
https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed

| Declaration | What it should mean | What it means in IE 10 |
| --- | --- | --- |
| (no flex declaration) | `flex: 0 1 auto` | `flex: 0 0 auto` |
| `flex: 1` | `flex: 1 1 0%` | `flex: 1 0 0px` |
| `flex: auto` | `flex: 1 1 auto` | `flex: 1 0 auto` |
| `flex: initial` | `flex: 0 1 auto` | `flex: 0 0 auto` |

**Comment by benjaminapetersen** [comment]
Fixed per [this PR](https://github.com/benjaminapetersen/layout.attrs/pull/14)
