### ISSUE TITLE
Needs display:inline-flex 

### ISSUE THREAD

**Issue by sg00dwin** [benjaminapetersen/layout.attrs#7]

**Comment by benjaminapetersen** [comment]
Thinking... I'm not sure I remember `display:inline-flex`.  Care to elaborate?

**Comment by sg00dwin** [comment]
Thinking that it should be included since it's an option
http://www.w3.org/TR/css-flexbox-1/#valdef-display-inline-flex

**Comment by benjaminapetersen** [comment]
Oh yeah, this should be pretty easy:

``` css
[flex-inline] {
  display: inline-flex;
}
```

``` html
<div flex-inline></div>
```

yeah?

**Comment by sg00dwin** [comment]
well, this touches on the conversation we talked about last week regarding the [row] attribute rule
so if

```
[flex-inline] {
  display: inline-flex;
}
```

then shouldn't display flex be

```
[flex] {
  display: flex;
}
```

Which would mean the flex:1 shorthand would be

```
[flex="1"] {
  flex: 1 1 0%; // each specified so browsers assign correct value
}
```

and other main ones that I think should be included 

```
[flex="auto"] {
  flex: 1 1 auto;
}
[flex="initial"] {
  flex: 0 1 auto;
}
[flex="none"] {
  flex: 0 0 auto;
}
```

**Comment by benjaminapetersen** [comment]
So a few more thoughts to add:

``` html
<!-- current -->
<div row>
  <div>1</div>
  <div flex>2</div>
  <div></div>
</div>

<!-- possible alternative? does this make it more clear? or is this too verbose? -->
<div flex direction="row" md-direction="column">
  <div>1</div>
  <div flex="1">2</div>
  <div></div>
</div>

<div flex direction="column" md-direction="row">
  <div>1</div>
  <div flex="1">2</div>
  <div></div>
</div>
```

I hesitate to make the markup significantly more verbose, but i like the word 'direction' as a keyword.

**Comment by sg00dwin** [comment]
What about introducing a flex-container attribute to designate the `display:flex`.

From https://drafts.csswg.org/css-flexbox-1/#box-model
"A flex container is the box generated by an element with a computed display of flex or inline-flex. ... A flex container establishes a new flex formatting context for its contents."

``` html
<!-- current -->
<div row>
  <div flex row>
    <div flex></div>
    <div flex></div>
  </div>
  <div flex column>
    <div flex></div>
    <div flex></div>
  </div>
</div>

<!-- becomes -->
<div flex-container row>
  <div flex row>
    <div flex></div>
    <div flex></div>
  </div>
  <div flex-container flex column>
    <div flex></div>
    <div flex></div>
  </div>
</div>
```

**Comment by benjaminapetersen** [comment]
Thats pretty much back to using `layout`, `layout row`, `layout column`, which we dropped because its "noisier" markup without actually adding functionality or improving readability.

``` html
<!-- old -->
<div layout row> </div>
<div layout column></div>

<!-- current -->
<div row> </div>
<div column> </div>
```

I still prefer the current, and probably wouldn't want to add a hyphenated word to go back to what was before, just to keep it light-weight.  Thoughts?

**Comment by benjaminapetersen** [comment]
@sg00dwin looks like our conversation here reflects at least some of what you are doing in the latest PR.

**Comment by benjaminapetersen** [comment]
Fixed per [this PR](https://github.com/benjaminapetersen/layout.attrs/pull/14)
